config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  get '/' => 'application#show'
  get '/apply' => 'application#apply'
  get 'background_check' => 'application#background_check'
  get 'done' => 'application#done'
  post '/users' => 'users#create'
end

app/models/annonymous_user.rb
class AnnonymousUser < ApplicationRecord
  belongs_to :user
  validates :user, presence: true
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/event.rb
class Event < ApplicationRecord
  validates :annonymous_key, presence: true
  validates :action, presence: true

  def annonymous_user
    @annonymous_user ||= AnnonymousUser.where(key: annonymous_key).first
  end

  def user
    @user ||= annonymous_user.try(:user)
  end
end

app/models/user.rb
class User < ApplicationRecord
  validates :first_name, presence: true
  validates :last_name, presence: true
  validates :email, presence: true, uniqueness: true
  validates :phone_number, presence: true, uniqueness: true
  validates :zip_code, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  include AnnonymousUserConcern

  protect_from_forgery with: :exception

  def show
    EventWorker.perform_async(annonymous_user_id, 'Onboarding - 1 homepage')
  end

  def apply
    EventWorker.perform_async(annonymous_user_id, 'Onboarding - 2 apply')
  end

  def background_check
    # TODO update user's background_check column
    EventWorker.perform_async(annonymous_user_id, 'Onboarding - 3 ask for background check')
  end

  def done
    EventWorker.perform_async(annonymous_user_id, 'Onboarding - 4 signed up')
  end

end

app/controllers/concerns/annonymous_user_concern.rb
module AnnonymousUserConcern
  def annonymous_user_id
    @annonymous_user_id ||= annonymous_user_id_cookie
  end

  def annonymous_user_id_cookie
    if cookies[:annonymous_id].nil?
      cookies[:annonymous_id] = srand
    end
    cookies[:annonymous_id]
  end


end

app/controllers/users_controller.rb
class UsersController < ActionController::Base
  include AnnonymousUserConcern

  def create
    @user = User.create(user_params)

    if @user.valid?
      AnnonymousUser.create(key: annonymous_user_id, user: @user)
      render json: @user
    else
      render json: {:errors => @user.errors.full_messages}, status:422
    end
  end

  private

  def user_params
    params.require(:user).permit(:first_name, :last_name, :email,:phone_number, :zip_code, :over_21, :access_car)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/application/apply.html.slim
.text-center
  h3 Please fill out the following information to apply to instacart
  p
    = form_for(User.new, remote: true, url: {action: 'create', controller: 'users'}, class: 'navbar-form.navbar-left', id: '#new_user') do |f|
      .form-group
        = f.label :first_name
        = f.text_field :first_name
      .form-group
        = f.label :last_name
        = f.text_field :last_name
      .form-group
        = f.label :email
        = f.text_field :email
      .form-group
        = f.label :phone_number
        = f.text_field :phone_number
      .form-group
        = f.label :zip_code
        = f.text_field :zip_code
      .form-group
        = f.label :over_21, 'Are you over 21?'
        = f.check_box :over_21
      .form-group
        = f.label :access_car, 'Do you have regular access to a car?'
        = f.check_box :access_car
      = f.submit("Apply")

javascript:
  $(document).ready(function() {
    return $("#new_user").on("ajax:success", function(e, data, status, xhr) {
      window.location = '/background_check'
    }).on("ajax:error", function(e, xhr, status, error) {
      return $("#new_user").append("<p>ERROR</p>");
    });
  });

app/views/application/background_check.html.slim
.text-center
  h3 instacart needs to run a background check to proceed with your application. Will you allow instacart to run the check?

  = form_for(User.new, url: {action: 'done', controller: 'application'}, method: 'get', class: 'navbar-form.navbar-left', id: '#background_check') do |f|
    .form-group
      = f.label :background_check, 'Do you consent to instacart running a background check?'
      = f.check_box :background_check
    = f.submit "Continue"

app/views/application/done.html.slim
.text-center
  h3 We have received your application and will contact you within the next week with the next steps
  p Thank you very much for applying.

app/views/application/show.html.slim
.text-center
  p Welcome to instacart. We are revolutionizing the grocery purchase model.
  p We can't do it alone. Apply now to earn money shopping and delivering groceries, giving customers more time to do what they love.
  = link_to "Apply Now", apply_path, class: 'btn btn-default'

  p As you can see, I will be focusing on the backend components more than the frontend. I will still store the user information in the session :)

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Ic</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <h1 class="text-center"> instacart </h1>
    <%= yield %>
  </body>
</html>